# -*- coding: UTF-8 -*-

import tkinter as tk
from tkinter import ttk
import tkinter.messagebox

# create root window
top_win = tk.Tk()

# naming root window
top_win.title('Hello World Window')

# resize root Window
win_size_pos = '800x600'

# win_size_pos = '360 x 60'
top_win.geometry(win_size_pos)

# ---------------------------------
title = 'My Label Frame'
lfm_step1 = ttk.Labelframe(
            top_win, text=title, width=240, height=500)
# lfm_step1.place(x=20, y=20)
lfm_step1.grid(row=0, column=0, padx=10, pady=10)

lbl_test = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test.grid(row=0, column=0, pady=5, padx=5)
lbl_test = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test.grid(row=1, column=0, pady=5, padx=5)
lbl_test = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test.grid(row=2, column=0, pady=5, padx=5)
lbl_test = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test.grid(row=3, column=0, pady=5, padx=5)
lbl_test = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test.grid(row=4, column=0, pady=5, padx=5)

lbl_test = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test.grid(row=0, column=1, pady=5, padx=5)
lbl_test = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test.grid(row=1, column=1, pady=5, padx=5)
lbl_test = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test.grid(row=2, column=1, pady=5, padx=5)
lbl_test = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test.grid(row=3, column=1, pady=5, padx=5)
lbl_test = tk.Label(lfm_step1, text='Oh! My god', bg='blue', fg='white')
lbl_test.grid(row=4, column=1, pady=5, padx=5)

title = 'My Label Frame generated by for'
lfm_step2 = ttk.Labelframe(
                top_win, text=title, width=240, height=500)
# lfm_step2.place(x=400, y=20)
lfm_step2.grid(row=0, column=1, padx=10, pady=10)

for r in range(5):
    for c in range(3):
        ent_row = tk.Entry(lfm_step2, show=None, width=8, bg='red', fg='white')
        # ent_row.place(x=20, y=20)
        ent_row.grid(row=r, column=c, padx=5, pady=5)
# ---------------------------------

# show window and get into event loop
top_win.mainloop()
